language: bash

services:
  - docker

matrix:
  include:
    - name: Drupal 8.8.x
      env: DOCKER_TAG="8.8"
    - name: Drupal 8.9.x
      env: DOCKER_TAG="8.9"
    - name: Drupal 9.0.x
      env: DOCKER_TAG="9.0"
    - name: Drupal 9.1.x
      env: DOCKER_TAG="9.1"

before_install:
  - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

script:
  - set -e
  - cd "${DOCKER_TAG%%.*}/${DOCKER_TAG}"
  - make
  - make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
    [[ -f ./Makefile ]] && make release;
    fi
