language: bash

services:
  - docker

matrix:
  include:
    - name: Drupal 8.8.x
      env: DOCKER_TAG="8.8"
    - name: Drupal 8.9.x
      env: DOCKER_TAG="8.9"
    - name: Drupal 9.0.x
      env: DOCKER_TAG="9.0"
    - name: Drupal 9.1-dev
      env: DOCKER_TAG="9.1"

script:
  - set -e
  - cd "${DOCKER_TAG%%.*}/${DOCKER_TAG}"
  - make
  - make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
    [[ -f ./Makefile ]] && make release;
    fi
